# Generated by Django 4.2.3 on 2025-07-26 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='Location',
            new_name='location',
        ),
    ]
