# Generated by Django 4.2.3 on 2025-08-09 08:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_promotion_tour_booking_check_in_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='star_rating',
            new_name='stars',
        ),
        migrations.AlterField(
            model_name='promotion',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 8, 8, 37, 38, 912855, tzinfo=datetime.timezone.utc)),
        ),
    ]
