# Generated by Django 4.2.3 on 2025-08-09 08:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_star_rating_hotel_stars_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 8, 8, 39, 34, 236852, tzinfo=datetime.timezone.utc)),
        ),
    ]
