# Generated by Django 4.2.7 on 2025-08-23 07:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_promotion_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 22, 7, 47, 25, 600330, tzinfo=datetime.timezone.utc)),
        ),
    ]
