# Generated by Django 4.2.24 on 2025-09-13 07:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_promotion_end_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('room_type', models.CharField(choices=[('standard', 'Standard Room'), ('deluxe', 'Deluxe Room'), ('suite', 'Suite'), ('family', 'Family Room'), ('executive', 'Executive Room'), ('villa', 'Villa')], default='standard', max_length=20)),
                ('bed_type', models.CharField(choices=[('single', 'Single Bed'), ('twin', 'Twin Beds'), ('double', 'Double Bed'), ('queen', 'Queen Bed'), ('king', 'King Bed')], default='single', max_length=20)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('capacity', models.IntegerField(default=2, help_text='Maximum number of guests')),
                ('size', models.IntegerField(default=0, help_text='Room size in square meters')),
                ('services', models.TextField(blank=True, help_text='Comma-separated list of services')),
                ('is_available', models.BooleanField(default=True)),
                ('is_non_smoking', models.BooleanField(default=True, help_text='Non-smoking room')),
                ('has_waiting_area', models.BooleanField(default=False, help_text='Has waiting area')),
                ('has_air_conditioning', models.BooleanField(default=True, help_text='Has air conditioning')),
                ('has_mini_bar', models.BooleanField(default=False, help_text='Has mini bar')),
                ('has_free_bottled_water', models.BooleanField(default=True, help_text='Provides free bottled water')),
                ('has_refrigerator', models.BooleanField(default=False, help_text='Has refrigerator')),
                ('has_tv', models.BooleanField(default=True, help_text='Has TV')),
                ('has_desk', models.BooleanField(default=True, help_text='Has desk')),
                ('has_hot_water', models.BooleanField(default=True, help_text='Has hot water')),
                ('has_private_bathroom', models.BooleanField(default=True, help_text='Has private bathroom')),
                ('has_shower', models.BooleanField(default=True, help_text='Has shower')),
                ('has_toiletries', models.BooleanField(default=True, help_text='Provides toiletries')),
                ('has_bathtub', models.BooleanField(default=False, help_text='Has bathtub')),
                ('has_hair_dryer', models.BooleanField(default=False, help_text='Has hair dryer')),
                ('has_bathrobes', models.BooleanField(default=False, help_text='Provides bathrobes')),
            ],
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_type',
            field=models.CharField(choices=[('hotel', 'Hotel'), ('flight', 'Flight'), ('tour', 'Tour'), ('car', 'Car Transfer')], max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='check_in_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='check_out_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='cartransfer',
            name='capacity',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='cartransfer',
            name='car_type',
            field=models.CharField(choices=[('sedan', 'Sedan'), ('suv', 'SUV'), ('van', 'Van'), ('luxury', 'Luxury')], default='sedan', max_length=20),
        ),
        migrations.AlterField(
            model_name='cartransfer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cars/'),
        ),
        migrations.AlterField(
            model_name='flightticket',
            name='available_seats',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Starting price for rooms', max_digits=10),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 13, 7, 28, 57, 781728, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='image',
            field=models.ImageField(default='promotions/default.jpg', upload_to='promotions/'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='promo_code',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='promotion_type',
            field=models.CharField(choices=[('hotel', 'Hotel'), ('flight', 'Flight'), ('tour', 'Tour'), ('car', 'Car Transfer'), ('general', 'General')], default='general', max_length=20),
        ),
        migrations.AlterField(
            model_name='tour',
            name='duration',
            field=models.CharField(help_text="e.g., '3 days, 2 nights'", max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='rooms/')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='home.room')),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='home.hotel'),
        ),
    ]
